replicaCount: 1

image:
  repository: "" 
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-key

service:
  type: ClusterIP
  port: 80 
  targetPort: 3000 

db:
  externalIP: "10.50.1.100" 

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: production