apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bezeq-app-staging
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/MrJoRnO/bezeq-infra-config.git'
    targetRevision: staging  
    path: charts/nodejs-api
    helm:
      valueFiles:
        - ../../envs/staging/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bezeq-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true