apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: openshift-console
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: openshift-console
  template:
    metadata:
      labels:
        app: openshift-console
    spec:
      containers:
        - name: console
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: BRIDGE_K8S_MODE
              value: {{ .Values.bridge.k8sMode | quote }}
            - name: BRIDGE_USER_AUTH
              value: {{ .Values.bridge.userAuth | quote }}