environment: dev

image:
  repository: "" 
  tag: "initial"

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi


env:
  NODE_ENV: development