apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-ext
spec:
  ports:
    - port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-db-ext
subsets:
  - addresses:
      - ip: {{ .Values.db.externalIP }}
    ports:
      - port: 1433