apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bezeq-app-ingress
  namespace: bezeq-dev 
  annotations:
    # האנוטציה הזו אומרת ל-EKS ליצור Application Load Balancer (ALB)
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bezeq-app # שם ה-Service של האפליקציה שלך
                port:
                  number: 80 # הפורט שה-Service מאזין לו