environment: dev

image:
  repository: "194636597980.dkr.ecr.eu-central-1.amazonaws.com/bezeq-app-dev-api" 
  tag: "7253fd4cd5dbd46082da3b7f94945b89ae877658"
  pullPolicy: IfNotPresent
  
env:
  NODE_ENV: development